### ISSUE TITLE
docker-compose and docker run file comes from source 

### ISSUE THREAD

**Issue by thatsk** [puppetlabs/puppetlabs-docker#173]
Hello Team,
its great if we have a parameter for running the docker-compose file from source parameter like
docker::composefile { 'docker-compose.yml':
  source => 'puppet://modules/docker-example.yml',
}

Like Logstash::configfile
https://github.com/elastic/puppet-logstash/blob/master/manifests/configfile.pp

**Comment by davejrt** [comment]
@thatsk I'd say this is a nice to have, but given you an already achieve this by simply using a file resource it is not going to be high on our priority list now. We'll be happy to review any PR's that add this functionality though

**Comment by thatsk** [comment]
composeconfigfile.pp
```YAML
define compose::configfile(
  $content = undef,
  $source = undef,
  $template = undef,
  $path = undef,
)
{
  include docker

  $owner = 'root'
  $group = 'root'
  $mode  = '0640'

  if($template)   { $config = template($template) }
  elsif($content) { $config = $content }
  else            { $config = undef }

  if($path) { $config_file = $path }
  else      { $config_file = "/opt/${name}" }

  if($config) {
    file { $config_file:
      content => $config,
      owner   => $owner,
      group   => $group,
      mode    => $mode,
    }
```
  }
  elsif($source) {
    file { $config_file:
      source  => $source,
      owner   => $owner,
      group   => $group,
      mode    => $mode,
    }
  }
}

**Comment by thatsk** [comment]
```YAML
docker::configfile:
  test:
    source: "puppet:///modules/mobi_logstash_configs/%{::domain}/04-jd-recording-status-logs.conf"

docker::docker_compose:
  test:
    compose_files: /opt/test
    ensure: present
```
