### ISSUE TITLE
Docker compose run on every config apply with extends

### ISSUE THREAD

**Issue by luckyraul** [puppetlabs/puppetlabs-docker#226]
## What you expected to happen?
one run only
## What happened?

docker-compose runs every config apply

https://github.com/puppetlabs/puppetlabs-docker/blob/master/lib/puppet/provider/docker_compose/ruby.rb#L23 

returns array with 0 containers because image in empty

## How to reproduce it?

```
version: '2'
services:
  base:
    image: someimage

  web:
    restart: unless-stopped
    extends: base

  cron:
    restart: unless-stopped
    extends: base
    command: run cron
```

```
docker_compose { '/somepath/docker-compose.yml':
  ensure  => present,
}
```
## Versions:

```
$ puppet --version

$ docker version

$ facter os

$ puppet module list
```

## Logs:
```
Paste any relevant logs from a puppet run
```
