### ISSUE TITLE
How do I install docker via YUM provider, not RPM? from private repositories on centos

### ISSUE THREAD

**Issue by thatsk** [puppetlabs/puppetlabs-docker#498]
## What you expected to happen?
Install docker ce packages via puppet

## What happened?

not able to see any error and it can't install docker

## How to reproduce it?
```YAML
profile::yum::extra_repo_hash:
  docker:
    baseurl: "http://test/pulp/repos/docker/"
    descr: "Docker Repo for stable packages "
    enabled: 1
    gpgcheck: 0
    name: docker

'docker::compose': present
'docker::compose::version': 1.19.0
'docker::ip_forward': false
'docker::version': 18.09.1-3.el7
'docker::manage_package': false
'docker::docker_ce_package_name': 'docker-ce'

'docker::labels':
  - stage=development

'docker::registry_auth::registries':
  'test':
    password: test
    username: build

docker::run_instance::instance:
  memcached:
    image: 'test'
    ensure: present
    net: host
    command: '-c 2048'
## Anything else we need to know?


## Versions:
<!-- Please paste in the output of these commands-->
```
$ puppet --version
4.10.12

$ facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    enabled => false
  }
}
