### ISSUE TITLE
debian10:  systemd 241-7 : docker-run.erb with exec_start \

### ISSUE THREAD

**Issue by aderumier** [puppetlabs/puppetlabs-docker#534]
Hi,

I have this hiera config
```
docker::run_instance::instance:
  prerender:
    image: 'magnetme/prerender-docker'
    ports: ['3000:3000']
    extra_parameters: ['--device /dev/dri', '--volume /dev/shm:/dev/shm', '--cap-add=SYS_ADMIN']
```

generate me this  systemd service

```
ExecStartPre=-/usr/bin/docker kill prerender
ExecStartPre=-/usr/bin/docker rm  prerender

ExecStart=/usr/bin/docker run \
        --net bridge -m 0b -p 3000:3000 \
 --device /dev/dri --volume /dev/shm:/dev/shm --cap-add=SYS_ADMIN \
        --name prerender \
        magnetme/prerender-docker \

ExecStop=-/usr/bin/docker stop --time=0 prerender
ExecStop=-/usr/bin/docker rm  prerender
```

It's working fine on debian 9, but on debian10 with systemd 241-7,

the \  at the end of exestart, take the execstop command.

(so try to start with something like "ExecStart=/usr/bin/docker run --net bridge -m 0b -p 3000:3000 --device /dev/dri --volume /dev/shm:/dev/shm --cap-add=SYS_ADMIN --name prerender magnetme/prerender-docker ExecStop=-/usr/bin/docker stop --time=0 prerender"

It seem to come from
templates/etc/systemd/system/docker-run.erb
```
ExecStart=/usr/bin/<%= @docker_command %> run \
        <%= @docker_run_flags %> \
        --name <%= @sanitised_title %> \
        <%= @image %> \
        <% if @command %> <%= @command %><% end %>
```
This is fixing the problem:

```
ExecStart=/usr/bin/<%= @docker_command %> run \
        <%= @docker_run_flags %> \
        --name <%= @sanitised_title %> \
        <%= @image %>
        <% if @command %> \ <%= @command %><% end %>
```
