### ISSUE TITLE
Unsupported docker compose file syntax version "3.7"

### ISSUE THREAD

**Issue by tobiashochguertel** [puppetlabs/puppetlabs-docker#575]
I receive with a docker-compose file which has version Number 3.7 setuped, an error.

```
 STDERR:
    Error: /Stage[main]/Project_status_monitor::Install/Docker_compose[Docker-Compose[Status-Monitor]]: Could not evaluate: Unsupported docker compose file syntax version "3.7"!
```

## Environment
mod 'puppetlabs-docker', '3.9.1'

```
version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "nginx_proxy_data_vhostd:/etc/nginx/vhost.d"
      - "nginx_proxy_data_confd:/etc/nginx/conf.d"
    networks:
      - default
      - frontend
```

The Bug is located in the following file: https://github.com/puppetlabs/puppetlabs-docker/blob/master/lib/puppet/provider/docker_compose/ruby.rb
