### ISSUE TITLE
 Error: No such file or directory if `restart: always` is set

### ISSUE THREAD

**Issue by ahoiroman** [puppetlabs/puppetlabs-docker#694]
## Describe the Bug
If I run a container using `Docker::run` setting `restart: always`, the following error is being thrown:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, No such file or directory - docker (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run.pp, line: 415, column: 25) (file: /etc/puppetlabs/code/environments/production/modules/docker/manifests/run_instance.pp, line: 8) on node example.org

## Expected Behavior
Creation of container without errors

## Steps to Reproduce
Create a container like

```
traefik:
  image: traefik:latest
  ensure: present
  restart: always
  ports:
  - 80:80
  - 443:443
  - 8080:8080
```

## Environment
 - Platform Debian

## Additional Context
`Docker::run` described with Foreman ENC in this example.
