### ISSUE TITLE
Unspecified class: Symbol

### ISSUE THREAD

**Issue by jellevandehaterd** [puppetlabs/puppetlabs-docker#715]
## Describe the Bug
Using module version 3.13.1 I get the following error when deploying a docker-compose.yml:

```
Info: Checking for compose project test
Error: /Stage[main]/Mycompany::Docker/Docker_compose[test]: Could not evaluate: Tried to load unspecified class: Symbol
```

## Expected Behavior
A successful check 

## Steps to Reproduce
Its not clear for me yet why this occurs but running 

`docker-compose -f docker-compose.yml -p test config`

and actually running the docker-compose.yml is no issue.
I do use a .env file next to the docker-compose.yml so I can use e.g. ${MY_VAR} in the compose file

## Environment
 - Version [3.13.1]
 - Platform [CentOS7]

## Additional Context
[YAML.safe_load](https://github.com/puppetlabs/puppetlabs-docker/blob/90725bb64b3254c5d69d0e18262f8d9f6c3b7c9d/lib/puppet/provider/docker_compose/ruby.rb#L23) probably is more strict than required.

My compose file:
```
version: "3.8"

services:
  test:
    image: traefik:v2.1.4
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "7"
    networks:
      - traefik-public
      - mynetwork
    env_file:
      - ${TRAEFIK_ENV_FILE}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ${TRAEFIK_CONFIG_DIR}/:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/pki/tls/private:/etc/ssl/certs:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.rule: "Host(\"my.host.name\")"
      traefik.http.routers.traefik.middlewares: traefik-https-redirect
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.traefik-secure.entrypoints: https
      traefik.http.routers.traefik-secure.rule: "Host(\"my.host.name\")"
      traefik.http.routers.traefik-secure.tls: "true"
      traefik.http.routers.traefik-secure.tls.options: myTLSOptions@file
      traefik.http.routers.traefik-secure.service: api@internal
    restart: always

```
