### ISSUE TITLE
Attempt to create volumes from Hiera does not work

### ISSUE THREAD

**Issue by MindTooth** [puppetlabs/puppetlabs-docker#793]
## Describe the Bug

Following the docs and various issues/PRs that changes the docs over time, I'm unable to create volumes using Hiera.

## Expected Behavior

By following the latest docs, I would expect Docker to create my volumes by instructions from Puppet.

## Steps to Reproduce
Add the following to a manifest file:
```yaml
classes:
  - docker::volumes

docker::root_dir: /srv/docker-data
docker::use_upstream_package_source: false

docker::volumes::volumes:
  mediafiles:
    ensure: present
  static:
    ensure: present
```

And have no volumes created, nor any mentions in the logs (`--debug --verbose`).

## Environment
 - Puppet: 6.26.0
 - puppet-docker: 4.2.1
 - Platform: Ubuntu 20.04

## Additional Context

Not sure what more you need, but just ask.
