### ISSUE TITLE
Could not find command 'docker swarm' with v6.0.0

### ISSUE THREAD

**Issue by ajurjevi** [puppetlabs/puppetlabs-docker#874]
With new module version (6.0.0) puppet run can't find docker swarm command on Debian 10 an 11.

```
Error: Could not find command 'docker swarm'
Error: /Stage[main]/Docker::Swarms/Docker::Swarm[cluster_manager]/Exec[Swarm init]/returns: change from 'notrun' to ['0'] failed: Could not find command 'docker swarm' (corrective)
```
Same thing works with version 5.1.0.

Configuration if needed:
```
docker::swarms::swarms:
  cluster_worker:
    join: true
    manager_ip: 'x.x.x.x'
    token: '---'
```
